foros/urls.py
from django.urls import include, path, re_path
from django.views.generic import ListView, DetailView
from .models import Foros
from .views import *

urlpatterns = [
]

informes/urls.py
from django.urls import path
from .models import *
from .views import *

urlpatterns = [
	path('<slug>/', detalle_informe, name='detalle-informe'),
	path('<slug>/informes/', lista_informes, name='lista-informes'),
	path('<slug>/documentos/', lista_documentos, name='lista-documentos'),
	path('<slug>/imagenes/', imagenes, name='imagenes'),
	path('<slug>/videos/', videos, name='videos'),
	path('<slug>/anexos/', anexos, name='anexos'),
]

interteam/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from notas import views as notas
from contrapartes import views as contra
from foros.views import *
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Administración Cluster'
admin.site.site_title = 'Cluster'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('taggit_autosuggest/', include('taggit_autosuggest.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('nested_admin/', include('nested_admin.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(
            template_name='registration/login.html'
        ), name='login'),
    path('accounts/profile/', perfil, name='perfil'),
    path('accounts/profile/editar/', contra.perfil_editar, name='perfil_editar'),
    path('accounts/logout/', notas.logout_page, name='logout'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('', notas.index),
    path('notas/', include('notas.urls')),
    path('contrapartes/', include('contrapartes.urls')),
    path('eventos/', include('agendas.urls')),
    path('foros/', include('foros.urls')),
    path('galerias/', include('galerias.urls')),
    path('publicaciones/', notas.publicaciones, name='publicacion-list'),
    path('publicaciones/<slug>', notas.publicacion_detalle, name='publicacion-detalle'),
    path('publicaciones/filtro/tema/<tema>', notas.filtro_temas_publi, name='filtro-temas-publi'),
    path('organizaciones/', notas.organizaciones),
    path('organizaciones/<slug>', notas.detalle_organizacion, name='detalle-organizacion'),
    path('biblioteca/', include('biblioteca.urls')),
    path('contacto/', notas.contacto, name='contacto'),
    path('informes/', include('informes.urls')),
    path('catalogo/', include('catalogo.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

informes/models.py
# -*- coding: UTF-8 -*-
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.template.defaultfilters import slugify
from sorl.thumbnail import ImageField
from django.contrib.auth.models import User
from embed_video.fields import EmbedVideoField

# Create your models here.
class Proyecto(models.Model):
	nombre = models.CharField(max_length=300)
	fecha_inicio = models.DateField()
	fecha_final = models.DateField()
	banner = ImageField(upload_to='informes/banner/',help_text='1350x500',blank=True,null=True)
	objectivos = RichTextUploadingField()
	descripcion = RichTextUploadingField()
	imagen_descripcion = ImageField(upload_to='informes/img-descripcion/',help_text='800x600',blank=True,null=True)
	coordinador_proyecto = models.CharField(max_length=300,verbose_name='Coordinador general del proyecto')
	email = models.EmailField()
	celular = models.CharField(max_length=50)
	responsable_proyecto = models.CharField(max_length=300)
	slug = models.SlugField(max_length=320,editable=False)
	user = models.ForeignKey(User,on_delete=models.DO_NOTHING)
	url_para_compartir = models.CharField(max_length=500)

	def __str__(self):
		return self.nombre

	def save(self, *args, **kwargs):
		self.slug = slugify(self.nombre)
		self.url_para_compartir = 'https://cluster-nicaragua.net/informes/' + self.slug
		return super(Proyecto, self).save(*args, **kwargs)

class Archivo(models.Model):
	proyecto = models.ForeignKey(Proyecto,on_delete=models.CASCADE)
	nombre = models.CharField(max_length=300)
	archivo = models.FileField(upload_to='informes/archivos/')

	class Meta:
		verbose_name = 'Archivo proyecto'
		verbose_name_plural = 'Archivos proyecto'

REPORTE_CHOICES = (('Informe técnico','Informe técnico'),('Informe financiero','Informe financiero'))

class Informe(models.Model):
	proyecto = models.ForeignKey(Proyecto,on_delete=models.CASCADE)
	nombre = models.CharField(max_length=300)
	tipo_reporte = models.CharField(max_length=50,choices=REPORTE_CHOICES)
	inicio = models.DateField()
	fin = models.DateField()
	fecha_informe = models.DateField()
	# nombre = models.CharField(max_length=300)
	archivo = models.FileField(upload_to='informes/informe/')

class RangoFechaImagenes(models.Model):
	proyecto = models.ForeignKey(Proyecto,on_delete=models.CASCADE)
	inicio = models.DateField()
	fin = models.DateField()

	class Meta:
		verbose_name = 'Fecha Imágen'
		verbose_name_plural = 'Fecha Imágenes'

class Imagenes(models.Model):
	rango = models.ForeignKey(RangoFechaImagenes,on_delete=models.CASCADE)
	nombre = models.CharField(max_length=300)
	archivo = ImageField(upload_to='informes/imgenes/')

	class Meta:
		verbose_name = 'Imágen'
		verbose_name_plural = 'Imágenes'

class Video(models.Model):
	proyecto = models.ForeignKey(Proyecto,on_delete=models.CASCADE)
	nombre = models.CharField(max_length=300)
	url = EmbedVideoField()

class Documento(models.Model):
	proyecto = models.ForeignKey(Proyecto,on_delete=models.CASCADE)
	nombre = models.CharField(max_length=300)
	descripcion = models.TextField()
	imagen = ImageField(upload_to='informes/imgenes/',null=True, blank=True)
	archivo = models.FileField(upload_to='informes/documentos/')

class HistoriasExito(models.Model):
	proyecto = models.ForeignKey(Proyecto,on_delete=models.CASCADE)
	nombre = models.CharField(max_length=200)
	foto = ImageField(upload_to='informes/historias-exito/',null=True, blank=True)
	texto = models.TextField()

	class Meta:
		verbose_name = 'Historia de éxito'
		verbose_name_plural = 'Historias de éxito'

class Monitoreo(models.Model):
	proyecto = models.ForeignKey(Proyecto,on_delete=models.CASCADE)
	nombre = models.CharField(max_length=200)
	foto = ImageField(upload_to='informes/monitoreo/',null=True, blank=True)

	class Meta:
		verbose_name = 'Anexo'
		verbose_name_plural = 'Anexos'

class ArchivosMonitoreo(models.Model):
	monitoreo = models.ForeignKey(Monitoreo,on_delete=models.CASCADE)
	archivo = models.FileField(upload_to='informes/monitoreo/')

	class Meta:
		verbose_name = 'Archivo'
		verbose_name_plural = 'Archivos'

informes/views.py
from django.shortcuts import render
from .models import *
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
import collections
from django.db.models.functions import ExtractYear 

# Create your views here.
@login_required
def detalle_informe(request,slug,template='informes/detalle.html'):
	object = get_object_or_404(Proyecto, slug=slug)
	rango = RangoFechaImagenes.objects.filter(proyecto = object.id)
	dict = collections.OrderedDict()
	for fecha in rango:
		imagenes = Imagenes.objects.filter(rango = fecha.id)
		dict[fecha.inicio,fecha.fin] = imagenes

	return render(request, template, locals())

@login_required
def lista_informes(request,slug,template='informes/informes.html'):
	object = get_object_or_404(Proyecto, slug=slug)
	object_list = Informe.objects.filter(proyecto__slug = slug)
	anios = object_list.annotate(year=ExtractYear('fecha_informe')).distinct('year').values_list('year', flat=True)
	return render(request, template, locals())

def lista_documentos(request,slug,template='informes/documentos.html'):
	object = get_object_or_404(Proyecto, slug=slug)
	object_list = Documento.objects.filter(proyecto__slug = slug)
	return render(request, template, locals())

def imagenes(request,slug,template='informes/imagenes.html'):
	object = get_object_or_404(Proyecto, slug=slug)
	rango = RangoFechaImagenes.objects.filter(proyecto = object.id)
	dict = collections.OrderedDict()
	for fecha in rango:
		imagenes = Imagenes.objects.filter(rango = fecha.id)
		dict[fecha.inicio,fecha.fin] = imagenes

	return render(request, template, locals())

def videos(request,slug,template='informes/videos.html'):
	object = get_object_or_404(Proyecto, slug=slug)
	object_list = Video.objects.filter(proyecto__slug = slug)
	return render(request, template, locals())

def anexos(request,slug,template='informes/anexos.html'):
	object = get_object_or_404(Proyecto, slug=slug)
	object_list = Monitoreo.objects.filter(proyecto__slug = slug)
	return render(request, template, locals())

templates/informes/anexos.html
{% extends "informes/base.html" %}
{% load thumbnail %}
{% load el_pagination_tags %}

{% block content %}
<style>

		.dropdown-item:focus, .dropdown-item:hover{
			background-color: #66b205;
			
		}
		.dlab-info-has .dropdown-menu a{
			color: black;
		}
		.site-button.outline.white:focus{
			color: #65b104;
		}
	</style>
<!-- inner page banner -->
<div class="dlab-bnr-inr dlab-bnr-inr-sm overlay-primary bg-pt" style="
{% thumbnail object.banner "1350x600" crop="center" as im %}
	background-image:url({{im.url}});
{% empty %} 
	background-image:url(http://via.placeholder.com/1350x500);
{% endthumbnail %}">
	<div class="container">
		<div class="dlab-bnr-inr-entry">
			<h2 class="text-white m-b10">Anexos</h2>
			<h5 class="text-white">{{object}}</h5>
			<!-- Breadcrumb row END -->
		</div>
	</div>
</div>
<!-- inner page banner END -->
<!-- contact area -->
<div class="content-block bg-white">
	<!-- Portfolio  -->
	<div class="section-full content-inner-2 portfolio text-uppercase" id="portfolio">

		<!--<div class="site-filters clearfix center  m-b40">
			<ul class="filters" data-toggle="buttons">
				<li data-filter="" class="btn active">
					<input type="radio">
					<a href="#" class="site-button-secondry radius-sm"><span>Todos</span></a> 
				</li>
				<li data-filter="2017" class="btn">
					<input type="radio">
					<a href="#" class="site-button-secondry radius-sm"><span>2017</span></a> 
				</li>
				<li data-filter="2017" class="btn">
					<input type="radio">
					<a href="#" class="site-button-secondry radius-sm"><span>2017</span></a> 
				</li>
				<li data-filter="2019" class="btn">
					<input type="radio">
					<a href="#" class="site-button-secondry radius-sm"><span>2019</span></a> 
				</li>
			</ul>
		</div>-->
		<div class="clearfix">
			<div class="container-fluid">
				<div class="row">
					{% paginate 12 object_list %}
					{% for anexo in object_list %}
					<div class="col-lg-3 col-md-6 col-sm-6 m-b30 wow zoomIn" data-wow-delay="0.2s">
							<div class="dlab-box portfolio-box">						
								<div class="dlab-media dlab-img-effect dlab-img-overlay1"> <img src="
									{% thumbnail anexo.foto "800x1100" crop="center" as im %}
									{{im.url}}
									{% empty %}
									http://via.placeholder.com/800x1100
									{% endthumbnail %}
								" alt="">
								
									<div class="dlab-info-has p-a15 bg-primary">
										<div class="btn-group dropup">
											<button type="button" class="site-button outline radius-xl white" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
												Descargar
											</button>
											<div class="dropdown-menu">
												{% for archivo in anexo.archivosmonitoreo_set.all %}
													<a class="dropdown-item" href="/media/{{archivo.archivo}}">Archivo #{{forloop.counter}}</a>
												{% endfor %}
											</div>
										</div>
									</div>
									<div class="overlay-bx">
										<div class="overlay-icon text-white"> 
											<h5>{{anexo.nombre}}</h5>
											<a href="/media/{{anexo.foto}}" class="mfp-link" title="Title Come Here"> <i class="ti-fullscreen icon-bx-xs"></i> </a>
										</div>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
					{% show_pages %}
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

templates/informes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="/static/images/logos/favicon.png"/>
	
	<!-- PAGE TITLE HERE -->
	<title>{{object}}</title>
	
	<!-- MOBILE SPECIFIC -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<!--[if lt IE 9]>
	<script src="js/html5shiv.min.js"></script>
	<script src="js/respond.min.js"></script>
	<![endif]-->
	
	<!-- STYLESHEETS -->
	{% block extra_css %}{% endblock extra_css %}
	<link rel="stylesheet" type="text/css" href="/static/informes/css/plugins.css">
	<link rel="stylesheet" type="text/css" href="/static/informes/css/style.css">
	<link rel="stylesheet" type="text/css" href="/static/informes/css/templete.css">
	<link class="skin" rel="stylesheet" type="text/css" href="/static/informes/css/skin/skin-1.css">
	
	<!-- REVOLUTION SLIDER CSS -->
	<link rel="stylesheet" type="text/css" href="/static/informes/plugins/revolution/revolution/css/settings.css">
	<link rel="stylesheet" type="text/css" href="/static/informes/plugins/revolution/revolution/css/navigation.css">
</head>
<body id="bg">
<div id="loading-area"><div class="la-anim-10"></div></div>
<div class="page-wraper">
	<!-- header -->
	<header class="site-header header-transparent mo-left">
		<!-- main header -->
		<div class="sticky-header main-bar-wraper navbar-expand-lg">
			<div class="main-bar clearfix ">
				<div class="container clearfix">
					<!-- website logo -->
					<!-- nav toggle button -->
					<button class="navbar-toggler collapsed navicon justify-content-end" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
						<span></span>
						<span></span>
						<span></span>
					</button>
					
					<!-- main nav -->
					<div class="header-nav navbar-collapse collapse justify-content-end" id="navbarNavDropdown">
						<ul class="nav navbar-nav">	
							<li><a href="{% url 'detalle-informe' object.slug %}">Proyecto</a></li>
							<li><a href="{% url 'lista-informes' object.slug %}">Informes</a></li>
							<li><a href="{% url 'lista-documentos' object.slug %}">Documentos</a></li>
							<li><a href="#">Galerías<i class="fa fa-chevron-down"></i></a>
								<ul class="sub-menu">
									<li><a href="{% url 'imagenes' object.slug %}" class="dez-page">Imágenes</a></li>
									<li><a href="{% url 'videos' object.slug %}" class="dez-page">Videos</a></li>
								</ul>	
							</li>
							<li><a href="{% url 'anexos' object.slug %}">Anexos</a></li>
						</ul>		 
					</div>
				</div>
			</div>
		</div>
		<!-- main header END -->
	</header>
	<!-- header END -->
	<!-- Content -->
	<div class="page-content">
		{% block content %}{% endblock content %}
	</div>
	<!-- Content END -->
	<!-- Footer -->
    <footer class="site-footer text-uppercase">

        <!-- footer bottom part -->
        <div class="footer-bottom bg-black">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 text-left ">
						<span>ASDENIC © {% now "Y" %}. Todos los derechos reservados. Desarrollado por </span>
						<a  href="http://www.simas.org.ni/">SIMAS</a>
					</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer END-->
	
    <!-- scroll top button -->
    <button class="scroltop fa fa-chevron-up" ></button>
	
</div>
<!-- JavaScript  files ========================================= -->
<script src="/static/informes/js/jquery.min.js"></script><!-- JQUERY.MIN JS -->
<script src="/static/informes/plugins/bootstrap/js/popper.min.js"></script><!-- BOOTSTRAP.MIN JS -->
<script src="/static/informes/plugins/bootstrap/js/bootstrap.min.js"></script><!-- BOOTSTRAP.MIN JS -->
<script src="/static/informes/plugins/wow/wow.js"></script><!-- BOOTSTRAP.MIN JS -->
<script src="/static/informes/plugins/bootstrap-select/bootstrap-select.min.js"></script><!-- FORM JS -->
<script src="/static/informes/plugins/bootstrap-touchspin/jquery.bootstrap-touchspin.js"></script><!-- FORM JS -->
<script src="/static/informes/plugins/magnific-popup/magnific-popup.js"></script><!-- MAGNIFIC-POPUP JS -->
<script src="/static/informes/plugins/imagesloaded/imagesloaded.js"></script><!-- MASONRY  -->
<script src="/static/informes/plugins/masonry/masonry-3.1.4.js"></script><!-- MASONRY  -->
<script src="/static/informes/plugins/masonry/masonry.filter.js"></script><!-- MASONRY  -->
<script src="/static/informes/plugins/owl-carousel/owl.carousel.js"></script><!-- OWL  SLIDER  -->
<script src="/static/informes/js/dz.carousel.js"></script><!-- SORTCODE FUCTIONS  -->
<script src="/static/informes/plugins/loading/anime.js"></script><!-- LOADING JS -->
<script src="/static/informes/plugins/loading/anime-app.js"></script><!-- LOADING JS -->
<script src="/static/informes/js/custom.js"></script><!-- CUSTOM FUCTIONS  -->
<script src="/static/informes/plugins/loading/anime.js"></script><!-- Tilt Jquery -->
<script src="/static/informes/plugins/loading/anime-app3.js"></script><!-- Tilt Jquery -->
<!-- REVOLUTION JS FILES -->
<script src="/static/informes/plugins/revolution/revolution/js/jquery.themepunch.tools.min.js"></script>
<script src="/static/informes/plugins/revolution/revolution/js/jquery.themepunch.revolution.min.js"></script>
<!-- Slider revolution 5.0 Extensions  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->
<script src="/static/informes/plugins/revolution/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script src="/static/informes/plugins/revolution/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
<script src="/static/informes/plugins/revolution/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script src="/static/informes/plugins/revolution/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script src="/static/informes/plugins/revolution/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<script src="/static/informes/plugins/revolution/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script src="/static/informes/plugins/revolution/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script src="/static/informes/plugins/revolution/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script src="/static/informes/plugins/revolution/revolution/js/extensions/revolution.extension.video.min.js"></script>
<script  src="/static/informes/js/rev.slider.js"></script>
{% block extra_js %}{% endblock extra_js %}
<script>
jQuery(document).ready(function() {
	'use strict';
	dz_rev_slider_1();
});	/*ready*/
$('.doc-carusel').owlCarousel({
    loop:true,
    margin:5,
    responsiveClass:true,
    navText: ['<i class="flaticon-left-arrow"></i>', '<i class="flaticon-right-arrow"></i>'],
    responsive:{
        0:{
            items:4,
            nav:true
        },
        600:{
            items:4,
            nav:false
        },
        1000:{
            items:4,
            nav:true,
            loop:false
        }
    }
});
$('.anexo-carusel').owlCarousel({
    loop:true,
    margin:5,
    responsiveClass:true,
    navText: ['<i class="flaticon-left-arrow"></i>', '<i class="flaticon-right-arrow"></i>'],
    responsive:{
        0:{
            items:4,
            nav:true
        },
        600:{
            items:4,
            nav:false
        },
        1000:{
            items:4,
            nav:true,
            loop:false
        }
    }
});
</script>
</body>
</html>

templates/informes/documentos.html
{% extends "informes/base.html" %}
{% load thumbnail %}
{% load el_pagination_tags %}


{% block content %}
<style>

		.doc-detalle .dlab-tilte{
			height: 48px;
		}
		.doc-detalle .dlab-desc{
			height: 112px;
		}
</style>
<!-- inner page banner -->
<div class="dlab-bnr-inr dlab-bnr-inr-sm overlay-primary bg-pt" style="{% thumbnail object.banner "1350x400" crop="center" as im %}
	background-image:url({{im.url}});
{% empty %} 
	background-image:url(http://via.placeholder.com/1350x500);
{% endthumbnail %}">
  <div class="container">
      <div class="dlab-bnr-inr-entry">
          <h2 class="text-white m-b10">Documentos</h2>
          <h5 class="text-white">{{object}}</h5>
          <!-- Breadcrumb row END -->
      </div>
  </div>
</div>
<!-- inner page banner END -->
<!-- contact area -->
<div class="content-block bg-white">
	<!-- Portfolio  -->
	<div class="section-full content-inner-2 portfolio text-uppercase" id="portfolio">

		<!--<div class="site-filters clearfix center  m-b40">
			<ul class="filters" data-toggle="buttons">
				<li data-filter="" class="btn active">
					<input type="radio">
					<a href="#" class="site-button-secondry radius-sm"><span>Todos</span></a> 
				</li>
				<li data-filter="2017" class="btn">
					<input type="radio">
					<a href="#" class="site-button-secondry radius-sm"><span>2017</span></a> 
				</li>
				<li data-filter="2017" class="btn">
					<input type="radio">
					<a href="#" class="site-button-secondry radius-sm"><span>2017</span></a> 
				</li>
				<li data-filter="2019" class="btn">
					<input type="radio">
					<a href="#" class="site-button-secondry radius-sm"><span>2019</span></a> 
				</li>
			</ul>
		</div>-->
		<div class="clearfix">
			<div class="container-fluid doc-detalle">
				<div class="row">
					{% paginate 12 object_list %}
					{% for doc in object_list|dictsortreversed:"id" %}
					<div class="col-lg-3 col-md-6 col-sm-6 m-b30 wow zoomIn" data-wow-delay="0.2s">
						{% thumbnail doc.imagen "250x272" crop="center" as im %}
						<div class="dlab-box-bg m-b30 box-hover" style="background-image: url({{im.url}})">
						{% empty %}
						<div class="dlab-box-bg m-b30 box-hover" style="background-image: url(http://via.placeholder.com/250x272)"></div>
						{% endthumbnail %}
							<div class="icon-bx-wraper center p-lr20 p-tb30">
								<div class="text-primary m-b30"> 
									<span class="icon-cell icon-sm"><i class="ti-ruler-pencil"></i></span> 
								</div>
								<div class="icon-content">
									<h5 class="dlab-tilte">{{doc.nombre}}</h5>
									<p class="dlab-desc">{{doc.descripcion|safe|truncatechars:100}}</p>
								</div>
							</div>
							<div class="icon-box-btn text-center">
								<a href="/media/{{doc.archivo}}" target="_blank" class="site-button btn-block">Descargar</a>
							</div>
						</div>
					</div>
					{% endfor %}

					{% show_pages %}
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock content %}

templates/informes/imagenes.html
{% extends "informes/base.html" %}
{% load thumbnail %}

{% block content %}
<!-- inner page banner -->
<div class="dlab-bnr-inr dlab-bnr-inr-sm overlay-primary bg-pt" style="
{% thumbnail object.banner "1350x600" crop="center" as im %}
	background-image:url({{im.url}});
{% empty %} 
	background-image:url(http://via.placeholder.com/1350x500);
{% endthumbnail %}">
	<div class="container">
		<div class="dlab-bnr-inr-entry">
			<h2 class="text-white m-b10">Galería de imágenes</h2>
			<h5 class="text-white">{{object}}</h5>
			<!-- Breadcrumb row END -->
		</div>
	</div>
</div>
<!-- inner page banner END -->
<!-- contact area -->
<div class="content-block bg-white">
	<!-- Portfolio  -->
	<div class="section-full bg-white p-t30 p-b30 portfolio section-galeria">
			<div class="container-fluid">
				<div class="site-filters clearfix center  m-b40">
					<ul class="filters" data-toggle="buttons">
						<li data-filter="" class="btn active">
							<input type="radio">
							<a href="#" class="site-button-secondry radius-sm"><span>Todas</span></a> 
						</li>
						{% for k in dict.keys %}
						<li data-filter="web-{{forloop.counter}}" class="btn">
							<input type="radio">
							<a href="#" class="site-button-secondry radius-sm"><span>{{k.0|date:"j M Y"}} al {{k.1|date:"j M Y"}}</span></a> 
						</li>
						{% endfor %}

					</ul>
				</div>
				<div class="clearfix">
					<ul id="masonry" class="dlab-gallery-listing gallery-grid-4 gallery mfp-gallery port-style1">
						
						{% for k,v in dict.items %}
						{% for img in v %}
						<li class="web-{{forloop.parentloop.counter}} design card-container col-lg-3 col-md-6 col-xs-12 col-sm-6 p-a0 wow zoomIn" data-wow-delay="0.2s">
							<div class="dlab-box dlab-gallery-box">
								<div class="dlab-media dlab-img-overlay1 dlab-img-effect">
									{% thumbnail img.archivo "330x220" crop="center" as im %}
										<a href="javascript:void(0);"> <img src="{{im.url}}"  alt=""> </a>
									{% empty %}
									  <a href="javascript:void(0);"> <img src="http://via.placeholder.com/330x220"  alt=""> </a>
									{% endthumbnail %}
									
									<div class="overlay-bx">
										<div class="overlay-icon align-b text-white text-left"> 
											<div class="text-white text-left port-box">
												<h5>{{img.nombre}}</h5>
												<a href="/media/{{img.archivo}}" class="mfp-link portfolio-fullscreen" title="{{img.nombre}}"><i class="ti-fullscreen icon-bx-xs"></i></a>
											</div>
										</div>
									</div>
								</div>
							</div>
						</li>
						{% endfor %}
						{% endfor %}
					</ul>
				</div>
			</div>
		</div>
</div>
<!-- contact area END -->
     
	
{% endblock content %}