biblioteca/urls.py
from django.urls import include, path
from .views import *

urlpatterns = [
	path('', list_biblioteca, name='list_biblioteca'),
	path('<slug>/', detail_biblioteca, name='biblioteca-detail'),
	path('filtro/tema/<tema>/', filtro_tema_biblioteca, name='filtro-tema-biblioteca'),
	path('filtro/categoria/<categoria>/', filtro_categoria_biblioteca, name='filtro-categoria-biblioteca'),
	]

foros/urls.py
from django.urls import include, path, re_path
from django.views.generic import ListView, DetailView
from .models import Foros
from .views import *

urlpatterns = [
]

interteam/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from notas import views as notas
from contrapartes import views as contra
from foros.views import *
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Administración Cluster'
admin.site.site_title = 'Cluster'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('taggit_autosuggest/', include('taggit_autosuggest.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('nested_admin/', include('nested_admin.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(
            template_name='registration/login.html'
        ), name='login'),
    path('accounts/profile/', perfil, name='perfil'),
    path('accounts/profile/editar/', contra.perfil_editar, name='perfil_editar'),
    path('accounts/logout/', notas.logout_page, name='logout'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('', notas.index),
    path('notas/', include('notas.urls')),
    path('contrapartes/', include('contrapartes.urls')),
    path('eventos/', include('agendas.urls')),
    path('foros/', include('foros.urls')),
    path('galerias/', include('galerias.urls')),
    path('publicaciones/', notas.publicaciones, name='publicacion-list'),
    path('publicaciones/<slug>', notas.publicacion_detalle, name='publicacion-detalle'),
    path('publicaciones/filtro/tema/<tema>', notas.filtro_temas_publi, name='filtro-temas-publi'),
    path('organizaciones/', notas.organizaciones),
    path('organizaciones/<slug>', notas.detalle_organizacion, name='detalle-organizacion'),
    path('biblioteca/', include('biblioteca.urls')),
    path('contacto/', notas.contacto, name='contacto'),
    path('informes/', include('informes.urls')),
    path('catalogo/', include('catalogo.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biblioteca/models.py
from django.db import models
from sorl.thumbnail import ImageField
from django.contrib.auth.models import User 
from django.template.defaultfilters import slugify
from ckeditor_uploader.fields import RichTextUploadingField
from notas.models import *

# Create your models here.
class Categoria(models.Model):
	nombre = models.CharField(max_length=250)
	def __str__(self):
		return u'%s' % self.nombre

class Archivos(models.Model):
	titulo = models.CharField(max_length=250)
	imagen = ImageField(upload_to='biblioteca/img/',null=True, blank=True)
	autor = models.CharField(max_length=250)
	editorial = models.CharField(max_length=250)
	lugar = models.CharField(max_length=250)
	fecha_publicacion = models.DateField()
	isbn = models.CharField(max_length=250,null=True,blank=True)
	numero_paginas = models.IntegerField()
	tematica = models.ForeignKey(Temas,on_delete=models.DO_NOTHING)
	categoria = models.ForeignKey(Categoria,on_delete=models.DO_NOTHING,null=True,blank=True)
	resumen = RichTextUploadingField()
	archivo = models.FileField(upload_to='biblioteca/archivos/')
	usuario = models.ForeignKey(User,on_delete=models.DO_NOTHING,editable=False)
	slug = models.SlugField(max_length=300,editable=False)

	def __str__(self):
		return u'%s' % self.titulo

	def save(self, *args, **kwargs):
		self.slug = slugify(self.titulo)
		return super(Archivos, self).save(*args, **kwargs)

	class Meta:
		verbose_name_plural = 'Archivos'

publicaciones/models.py
from django.db import models
from sorl.thumbnail import ImageField
from django.contrib.auth.models import User
from notas.models import *
from ckeditor_uploader.fields import RichTextUploadingField
from django.template.defaultfilters import slugify

# Create your models here.
class Informacion(models.Model):
	nombre = models.CharField(max_length=250)

	def __str__(self):
		return u'%s' % self.nombre

	class Meta:
		verbose_name_plural = 'Información'

class Herramientas(models.Model):
	nombre = models.CharField(max_length=250)

	def __str__(self):
		return u'%s' % self.nombre

	class Meta:
		verbose_name_plural = 'Herramientas'

class Publicacion(models.Model):
	titulo = models.CharField(max_length=250)
	imagen = ImageField(upload_to='publicaciones/img/',null=True, blank=True,help_text='Tamaño recomendado: 360x390')
	# archivo = models.FileField(upload_to='publicaciones/archivos/')
	resumen = RichTextUploadingField()
	tematica = models.ForeignKey(Temas,on_delete=models.DO_NOTHING)
	usuario = models.ForeignKey(User,on_delete=models.DO_NOTHING)
	slug = models.SlugField(max_length=250,editable=False)
	publicada = models.BooleanField()
	correo_enviado = models.BooleanField(editable=False, null=True)
	informacion = models.ForeignKey(Informacion,on_delete=models.DO_NOTHING,null=True, blank=True)
	herramienta = models.ForeignKey(Herramientas,on_delete=models.DO_NOTHING,null=True, blank=True)

	def __str__(self):
		return u'%s' % self.titulo

	def save(self, *args, **kwargs):
		self.slug = slugify(self.titulo)
		return super(Publicacion, self).save(*args, **kwargs)

	class Meta:
		verbose_name_plural = 'Biblioteca'
		verbose_name = 'Biblioteca'

class ArchivosPublicacion(models.Model):
	publicacion = models.ForeignKey(Publicacion,on_delete=models.CASCADE)
	nombre = models.CharField(max_length=250)
	archivo_pdf = models.FileField(upload_to='publicaciones/archivos/')

	def __str__(self):
		return u'%s' % self.nombre

	class Meta:
		verbose_name_plural = 'Archivos'

class AudiosPublicacion(models.Model):
	publicacion = models.ForeignKey(Publicacion,on_delete=models.CASCADE)
	nombre = models.CharField(max_length=250)
	archivo_audio = models.FileField(upload_to='publicaciones/audios/')

	def __str__(self):
		return u'%s' % self.nombre

	class Meta:
		verbose_name_plural = 'Audios'

class VideosPublicacion(models.Model):
	publicacion = models.ForeignKey(Publicacion,on_delete=models.CASCADE)
	nombre = models.CharField(max_length=250)
	url = models.URLField()

	def __str__(self):
		return u'%s' % self.nombre

	class Meta:
		verbose_name_plural = 'Videos'

publicaciones/forms.py
# -*- coding: utf-8 -*-
from django.db import models
from .models import *
from django import forms
from contrapartes.models import *

class PublicacionForm(forms.ModelForm):
	class Meta:
		model = Publicacion
		exclude = ('usuario',)

class ArchivosPubliForm(forms.ModelForm):
	class Meta:
		model = ArchivosPublicacion
		fields = '__all__'

class AudiosPubliForm(forms.ModelForm):
	class Meta:
		model = AudiosPublicacion
		fields = '__all__'

class VideosPubliForm(forms.ModelForm):
	class Meta:
		model = VideosPublicacion
		fields = '__all__'

def organizaciones():
	lista = []
	foo = Publicacion.objects.order_by('usuario__userprofile__contraparte').distinct('usuario__userprofile__contraparte').values_list('usuario__userprofile__contraparte__id', flat=True)
	for x in Contraparte.objects.filter(id__in=foo):
		lista.append((x.id,x.siglas))
	return lista

class FiltrosBiblioteca(forms.Form):
	def __init__(self, *args, **kwargs):
		super(FiltrosBiblioteca, self).__init__(*args, **kwargs)
		self.fields['informacion'] = forms.ModelMultipleChoiceField(queryset=Informacion.objects.order_by('nombre'), required=False)
		self.fields['herramientas'] = forms.ModelMultipleChoiceField(queryset=Herramientas.objects.order_by('nombre'), required=False)
		self.fields['organizaciones'] = forms.MultipleChoiceField(choices=organizaciones(), required=False)

biblioteca/views.py
from django.shortcuts import render
from .models import *
from django.db.models import Q
from notas.models import *

# Create your views here.
def list_biblioteca(request, template='biblioteca.html'):
	if request.GET.get('buscar'):
		q = request.GET['buscar']
		object_list = Archivos.objects.filter(Q(titulo__icontains = q) | 
										Q(autor__icontains = q) |
										Q(editorial__icontains = q)|
										Q(lugar__icontains = q) |
										Q(isbn__icontains = q) |
										Q(tematica__nombre__icontains = q)|
										Q(resumen__icontains = q) |
										Q(usuario__userprofile__contraparte__siglas__icontains = q)).order_by('-id')
	else:
		object_list = Archivos.objects.order_by('-id')

	count_publi = Archivos.objects.all().count()
	dic_temas = {}
	for tema in Temas.objects.all():
		count = Archivos.objects.filter(tematica = tema).count()
		if count != 0:
			dic_temas[tema] = count

	dic_cat = {}
	for cat in Categoria.objects.all():
		count = Archivos.objects.filter(categoria = cat).count()
		if count != 0:
			dic_cat[cat] = count

	return render(request, template, locals())

def filtro_tema_biblioteca(request, tema, template='biblioteca.html'):
	if request.GET.get('buscar'):
		q = request.GET['buscar']
		object_list = Archivos.objects.filter(Q(titulo__icontains = q) | 
										Q(autor__icontains = q) |
										Q(editorial__icontains = q)|
										Q(lugar__icontains = q) |
										Q(isbn__icontains = q) |
										Q(tematica__nombre__icontains = q)|
										Q(resumen__icontains = q)).order_by('-id')
	else:
		object_list = Archivos.objects.filter(tematica__nombre = tema)

	count_publi = Archivos.objects.all().count()
	dic_temas = {}
	for tema in Temas.objects.all():
		count = Archivos.objects.filter(tematica = tema).count()
		if count != 0:
			dic_temas[tema] = count

	dic_cat = {}
	for cat in Categoria.objects.all():
		count = Archivos.objects.filter(categoria = cat).count()
		if count != 0:
			dic_cat[cat] = count

	return render(request, template, locals())

def filtro_categoria_biblioteca(request, categoria, template='biblioteca.html'):
	if request.GET.get('buscar'):
		q = request.GET['buscar']
		object_list = Archivos.objects.filter(Q(titulo__icontains = q) | 
										Q(autor__icontains = q) |
										Q(editorial__icontains = q)|
										Q(lugar__icontains = q) |
										Q(isbn__icontains = q) |
										Q(tematica__nombre__icontains = q)|
										Q(resumen__icontains = q)).order_by('-id')
	else:
		object_list = Archivos.objects.filter(categoria__nombre = categoria)

	count_publi = Archivos.objects.all().count()
	dic_temas = {}
	for tema in Temas.objects.all():
		count = Archivos.objects.filter(tematica = tema).count()
		if count != 0:
			dic_temas[tema] = count

	dic_cat = {}
	for cat in Categoria.objects.all():
		count = Archivos.objects.filter(categoria = cat).count()
		if count != 0:
			dic_cat[cat] = count

	return render(request, template, locals())

def detail_biblioteca(request, slug, template='detalle_biblioteca.html'):
	object = Archivos.objects.get(slug=slug)

	return render(request, template, locals())

templates/biblioteca.html
{% extends "base.html" %}
{% load thumbnail %}
{% load el_pagination_tags %}

{% block content %}
<style type="text/css">
.fund-pagination span {
    height: 40px;
    display: inline-block;
    width: 40px;
    line-height: 38px;
    text-align: center;
    border: 1px solid #cccccc;
    border-radius: 100%;
    color: #1e3042;
    margin-right: 15px;
}
.filter-options > li > a:before {
    content: none;
}
</style>
<div class="banner-area banner-area--events all-text-white text-center">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-title">Biblioteca virtual</h1>
                <ul class="fund-breadcumb">
                    <li><a href="/">Inicio</a> </li>
                    <li>Biblioteca</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="main-content section-padding">
    <div class="container">
        <div class="row list-publicaciones"> 
            <div class="col-md-3" >
                <form class="search-form widget" action='.' method='GET'>
                    <input type="search" placeholder="Buscar" name="buscar" class="form-control search-form__input" {% if q %}value="{{q}}"{% endif %} />
                    <button type="submit" class="search-form__submit"><i class="fa fa-search base-color"></i> </button>
                </form>
                <aside class="sidebar">
                    <div class="widget widget--category">
                        <div class="widget__heading">
                            <h4 class="widget__title">TEMAS</h4>
                        </div>
                        <div class="widget__text-content">
                            <ul class="filter-options">
                                <li><a href="/biblioteca/" class="pdr10 filter-options__item filter" data-filter=".todos"><i class="fa fa-tags"></i> Todos</a><span class="post-count">{{count_publi}}</span></li>
                                {% for x,y in dic_temas.items %}
                                <li><a href="{% url 'filtro-tema-biblioteca' x %}" class="pdr10 filter-options__item filter" data-filter=".{{x.id}}"><i class="fa fa-tags"></i> {{x}}</a><span class="post-count">{{y}}</span></li>
                                {% endfor %}
                               
                            </ul>


                        </div>
                    </div>
                    
                </aside>  
                <aside class="sidebar">
                    <div class="widget widget--category">
                        <div class="widget__heading">
                            <h4 class="widget__title">CATEGORÍAS</h4>
                        </div>
                        <div class="widget__text-content">
                            <ul class="filter-options">
                                <li><a href="/biblioteca/" class="pdr10 filter-options__item filter" data-filter=".todos"><i class="fa fa-tags"></i> Todos</a><span class="post-count">{{count_publi}}</span></li>
                                {% for x,y in dic_cat.items %}
                                <li><a href="{% url 'filtro-categoria-biblioteca' x %}" class="pdr10 filter-options__item filter" data-filter=".{{x.id}}"><i class="fa fa-tags"></i> {{x}}</a><span class="post-count">{{y}}</span></li>
                                {% endfor %}
                               
                            </ul>
                        </div>
                    </div>
                    
                </aside>   
            </div>
            <div class="col-md-9">
                {% paginate 6 object_list %}
                {% for object in object_list %}
                     <div class="col-md-4 col-sm-12">
                        <div class="div">
                            <div class="our-causes">
                                <div class="our-causes__image-wrap">
                                    {% thumbnail object.imagen "360x390" crop="center" as im %}
                                        <img src="{{im.url}}" class="our-causes__image" alt="">
                                    {% empty %}   
                                      <img src="http://via.placeholder.com/360x390" class="our-causes__image" alt="">
                                    {% endthumbnail %}
                                </div>

                                <div class="our-causes__text-content text-center">

                                    <h5 class=" our-causes__title"><a data-toggle="modal" href='{% url 'biblioteca-detail' object.slug %}'>{{object.titulo}}</a></h5>
                                </div>
                            </div>
                        </div>
                    </div>                  
                {% endfor %}                   
                {% if not object_list %}
                    <p>No hay resultados</p>
                {% endif %}
                
                </div>

        </div>
        <div class="fund-pagination mb30">
            {% show_pages %}
        </div>
        
    </div>
</div>
{% endblock content %}

templates/contacto.html
{% extends "base.html" %}

{% block content %}
	
{% endblock content %}

templates/detalle_biblioteca.html
{% extends "base.html" %}
{% load thumbnail %}

{% block content %}
<div class="banner-area banner-area--blog all-text-white text-center">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-title">Biblioteca virtual</h1>
                <ul class="fund-breadcumb">
                    <li><a href="/">Inicio</a> </li>
                    <li><a href="/biblioteca/">Biblioteca</a> </li>
                    <li>Documento</li>

                </ul>
            </div>
        </div>
    </div>
</div>
<div class="main-content section-padding">
    <div class="container">
        <div class="row wow fadeInUpXsd" data-wow-duration=".7s" data-wow-delay=".3s">
        	<div class="col-xs-12 col-md-4">
        		{% thumbnail object.imagen "360x390" crop="center" as im %}
			        <img class="img-thumbnail" src="{{im.url}}" class="our-causes__image" alt="" width="100%">
			    {% empty %}   
			      <img class="img-thumbnail" src="http://via.placeholder.com/360x390" class="our-causes__image" alt="" width="100%">
			    {% endthumbnail %}
			    <br>
			    <br>
			    <div class="all-text-white">
                     <a href="/media/{{object.archivo}}" class="btn base-bg btn-lg btn-block" >Descargar Documento</a>
                </div>
                <br>

        	</div>
        	<div class="col-xs-12 col-md-8">
        		<div class="panel panel-success">
        			<div class="panel-body">
        				<h3 class=" base-color">
        					{{object.titulo}}
        				</h3>
        				
        				<h4>
        					Por: <span class="base-color">{{object.autor}}</span>
        				</h4>
        				<h3>Resumen:</h3>
        				<hr>
        				<div>
        					<p>{{object.resumen|safe}}</p>
        					<h3>Detalles:</h3>
        					<hr>
        					<div class="table-responsive">
        						<table class="table table-hover table-striped">
        							<tbody>
        								<tr>
        									<td>Editorial</td>
        									<td>{{object.editorial}}</td>
        								</tr>
        								<tr>
        									<td>Lugar</td>
        									<td>{{object.lugar}}</td>
        								</tr>
        								<tr>
        									<td>Fecha de publicación</td>
        									<td>{{object.fecha_publicacion}}</td>
        								</tr>
                                        {% if object.isbn %}
        								<tr>
        									<td>isbn</td>
        									<td>
												{{object.isbn}}
        									</td>
        								</tr>
                                        {% endif %}
        								<tr>
        									<td>No. Páginas</td>
        									<td>{{object.numero_paginas}} páginas</td>
        								</tr>
        								<tr>
        									<td>Temas</td>
        									<td>{{object.tematica}}</td>
        								</tr>
        							</tbody>
        						</table>
        					</div>
        				</div>
        				
        			</div>
        		</div>
        	</div>
        </div>
    </div>
</div>

{% endblock content %}

templates/detalle_galeria.html
{% extends "base.html" %}
{% load thumbnail %}
{% load embed_video_tags %}

{% block content %}
<div class="banner-area banner-area--blog all-text-white text-center">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-title">{{object.titulo}}</h1>
                <ul class="fund-breadcumb">
                    <li><a href="/">Inicio</a> </li>
                    <li><a href="/galerias/imagenes/">Galería de imágenes</a> </li>

                </ul>
            </div>
        </div>
    </div>
</div>

<div class="main-content section-padding">
    <div class="container">
        <div class="row wow fadeInUpXsd" data-wow-duration=".7s" data-wow-delay=".3s">
            <div class="col-md-12">
                <div class="row row-eq-height" id="mixitup-grid">
                    {% for galeria in object.imagenes_set.all %}
                    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-6 mix all charity natureal" style="display: inline-block;" data-bound="">
                            {% thumbnail galeria.imagen "800" crop="center" as im %}
                                <a class="gallery-item cboxElement" title="{{galeria.nombre}}" href="{{im.url}}">
                             {% endthumbnail %}
                            <!--<a class="gallery-item cboxElement" href="/media/{{galeria.imagen}}">-->
                            {% thumbnail galeria.imagen "380x250" crop="center" as im %}
                                <img class="gallery-item__photo lazy" src="{{im.url}}" style="display: inline; " >
                             {% endthumbnail %}
                            <div class="loader loder-hide"></div>
                        </a><!--/.portfolio-item-->
                       
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

templates/publicacion_detalle.html
{% extends "base.html" %}
{% load thumbnail %}
{% load embed_video_tags %}

{% block content %}
<style>
#contenido ul, #contenido ol {
     list-style: disc;
}
</style>
<div class="banner-area banner-area--blog all-text-white text-center">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-title">Biblioteca</h1>
                <ul class="fund-breadcumb">
                    <li><a href="/">Inicio</a> </li>
                    <li><a href="/publicaciones/">Biblioteca</a> </li>
                    <li>Detalle</li>

                </ul>
            </div>
        </div>
    </div>
</div>
<div class="main-content section-padding">
    <div class="container">
        <div class="row wow fadeInUpXsd" data-wow-duration=".7s" data-wow-delay=".3s">
        	<div class="col-xs-12 col-md-4">
        		{% thumbnail object.imagen "360x390" crop="center" as im %}
			        <img class="img-thumbnail" src="{{im.url}}" class="our-causes__image" alt="" width="100%">
			    {% empty %}
			      <img class="img-thumbnail" src="http://via.placeholder.com/360x390" class="our-causes__image" alt="" width="100%">
			    {% endthumbnail %}
			    <br>
			    <br>

        	</div>
        	<div class="col-xs-12 col-md-8">
        		<div class="panel panel-success">
        			<div class="panel-body">
        				<h3 class=" base-color">
        					{{object.titulo}}
        				</h3>
        				<h3>Resumen:</h3>
        				<hr>
        				<div id="contenido">
        					<p>{{object.resumen|safe}}</p>
    					</div>

    					{% if object.archivospublicacion_set.all %}
						<h3>Archivos</h3><hr>
    					<div>
    						<ul>
    							{% for pdf in object.archivospublicacion_set.all %}
    							<li><a href="/media/{{pdf.archivo_pdf}}" class="base-color" target="_blank">{{pdf.nombre}}</a></li>
    							{% endfor %}
							</ul>
    					</div>
    					<br><br>
    					{% endif %}

    					{% if object.audiospublicacion_set.all %}
						<h3>Audios</h3><hr>
    					<div>
							<ul>
    							{% for audio in object.audiospublicacion_set.all %}
    							<li><a href="/media/{{audio.archivo_audio}}" target="_blank">{{audio.nombre}}</a></li>
    							{% endfor %}
							</ul>
    					</div>

    					<br><br>
    					{% endif %}

    					{% if object.videospublicacion_set.all %}
						<h3>Videos</h3><hr>
    					<div>
							<ul>
    							{% for video in object.videospublicacion_set.all %}
    							<div class="col-md-6">
    								{% video video.url '100% x 240px' %}
    							</div>
    							{% endfor %}
							</ul>
    					</div>
    					{% endif %}
        			</div>
        		</div>
        	</div>
        </div>
    </div>
</div>
{% endblock content %}

templates/publicaciones.html
{% extends "base.html" %}
{% load thumbnail %}
{% load el_pagination_tags %}

{% block content %}
<style type="text/css">
.fund-pagination span {
    height: 40px;
    display: inline-block;
    width: 40px;
    line-height: 38px;
    text-align: center;
    border: 1px solid #cccccc;
    border-radius: 100%;
    color: #1e3042;
    margin-right: 15px;
}
.filter-options > li > a:before {
    content: none;
}
</style>
<div class="banner-area banner-area--events all-text-white text-center">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-title">Biblioteca</h1>
                <ul class="fund-breadcumb">
                    <li><a href="/">Inicio</a> </li>
                    <li><a href="#">Lista</a> </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="main-content section-padding">
    <div class="container">
        <div class="filtercat mb20">
            <form class="" action="/publicaciones/" method="GET">{% comment %} {% csrf_token %} {% endcomment %}
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="form-group">
                                <div class="input-group__label">{{form.informacion.label}}</div>
                                {{form.informacion}}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="input-group">
                                <div class="input-group__label">{{form.herramientas.label}}</div>
                                {{form.herramientas}}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="input-group">
                                <div class="input-group__label">{{form.organizaciones.label}}</div>
                                {{form.organizaciones}}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-3">
                            <div class="input-group">
                                <label for=""></label>
                                <br>
                                <button class="btn" type="submit">Consultar</button>
                            </div>
                        </div>
                    </div>
                </div>

            </form>
        </div>

        <div class="row list-publicaciones">
            <div class="col-md-3" >
                <aside class="sidebar">
                    <form class="search-form widget" action='.' method='GET'>
                        <input type="search" placeholder="Buscar" name="buscar" class="form-control search-form__input" {% if q %}value="{{q}}"{% endif %} />
                        <button type="submit" class="search-form__submit"><i class="fa fa-search base-color"></i> </button>
                    </form>
                    <div class="widget widget--category">
                        <div class="widget__heading">
                            <h4 class="widget__title">TEMAS</h4>
                        </div>
                        <div class="widget__text-content">
                            <ul class="filter-options">
                                <li><a href="/publicaciones/" class="pdr10 filter-options__item filter" data-filter=".todos"><i class="fa fa-tags"></i> Todos</a><span class="post-count">{{count_publi}}</span></li>
                                {% for x,y in dic_temas.items %}
                                <li><a href="{% url 'filtro-temas-publi' x %}" class="pdr10 filter-options__item filter
                                " data-filter=".{{x.id}}"><i class="fa fa-tags"></i> {{x}}</a><span class="post-count">{{y}}</span></li>
                                {% endfor %}

                            </ul>


                        </div>
                    </div>

                </aside>
            </div>
            <div class="col-md-9">
                {% paginate 6 object_list %}
                {% for object in object_list %}
                     <div class="col-md-4 col-sm-12">
                        <div class="div">
                            <div class="our-causes ">
                                <div class="our-causes__image-wrap">
                                    {% thumbnail object.imagen "360x390" crop="center" as im %}
                                        <img src="{{im.url}}" class="our-causes__image" alt="">
                                    {% empty %}
                                      <img src="http://via.placeholder.com/360x390" class="our-causes__image" alt="" width="100%">
                                    {% endthumbnail %}
                                </div>

                                <div class="our-causes__text-content text-center">

                                    <h5 class=" our-causes__title line_2"><a data-toggle="modal" href='{% url 'publicacion-detalle' object.slug %}'>{{object.titulo}}</a></h5>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% if not object_list %}
                    <p>No hay resultados</p>
                {% endif %}

            </div>


        </div>
        <div class="fund-pagination mb30">
            {% show_pages %}
        </div>

    </div>
</div>
{% endblock content %}
{% block extra_js %}

<script type="text/javascript">
    $('#id_informacion, #id_herramientas, #id_organizaciones').addClass('form-control');
    $('#id_informacion, #id_herramientas, #id_organizaciones').select2();
</script>
{% endblock extra_js %}